jobs:
  include:
  - name: lint scrobbler
    language: python
    python: 3.8.5
    before_script:
      - cd heos-track-scrobbler
      - pip install -r requirements.txt
      - pip install -r dev-requirements.txt
    script:
      - pylint main.py last_fm/ models/
  - name: lint listener
    language: node_js
    node_js: 12.18
    before_script:
      - cd heos-track-listener
      - npm install
    script:
      - npm run lint
  - name: audit scrobbler
    language: python
    python: 3.8.5
    before_script:
      - cd heos-track-scrobbler
      - pip install --upgrade pip py
      - pip install -r requirements.txt
      - pip install safety==1.10.3
    script:
      - safety check --full-report
  - name: audit listener
    language: node_js
    node_js: 12.18
    before_script:
      - cd heos-track-listener
      - npm install
    script:
      - npm audit
