version: "3"

services:
  heos-track-listener:
    build:
      context: heos-track-listener
    image: heos-track-listener:latest
    command: npm start
    environment:
      MONGO_DB: heosScrobbler
      REDIS_CHANNEL: heosScrobbler
    env_file:
      - heos-track-listener/.env
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
      - redis
  heos-track-scrobbler:
    build:
      context: heos-track-scrobbler
    image: heos-track-scrobbler:latest
    command: python main.py
    environment:
      PYTHONUNBUFFERED: 1
      MONGO_DB: heosScrobbler
      REDIS_CHANNEL: heosScrobbler
    env_file:
      - heos-track-scrobbler/.env
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.0-xenial
    command: --port $MONGO_PORT
    env_file:
      - mongo/.env
    restart: always
    network_mode: "host"
    volumes:
      - mongo_data:/data/db
      - ./mongo/initialize.js:/usr/src/initialize.js
  mongo-express:
    image: mongo-express:0.49
    env_file:
      - mongo-express/.env
    restart: always
    network_mode: "host"
    depends_on:
      - mongo
  redis:
    image: redis:5.0-alpine
    command: --port $REDIS_PORT
    env_file:
      - redis/.env
    restart: always
    network_mode: "host"

volumes:
  mongo_data:
