version: "3"

services:
  heos-track-listener:
    build:
      context: heos-track-listener
    image: heos-track-listener:latest
    command: npm start
    environment:
      HEOS_SUBMIT_BASE_URL: http://localhost:5000
    env_file:
      - heos-track-listener/.env
    restart: always
    network_mode: "host"
    depends_on:
      - heos-track-scrobbler
  heos-track-scrobbler:
    build:
      context: heos-track-scrobbler
    image: heos-track-scrobbler:latest
    command: flask run --host=0.0.0.0 --port=80
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_APP: scrobbler.py
    env_file:
      - heos-track-scrobbler/.env
    restart: always
    network_mode: "host"
